### PR TITLE
Implemented Input validation for the parse function and improved function doc

### PR DESCRIPTION
**Pull request by AlexJuca**

### CODE REVIEW

**Comment by fklement** [comment]
@AlexJuca Thanks for your contribution. I'll have a look at it by the end of today.

**Comment by AlexJuca** [comment]
Awesome, looking forward to your feedback.

**Review by fklement — APPROVED** [review]

**Review by fklement — APPROVED** [review]
Simple and effective but still not preventing against all possible manipulations.
E.g. someone would be still able to do sth like:
```elixir
%Hades.Command{scan_types: [:a, :b], target: ""}
```
It would be nice if you also could implement a check for the `scan_types`.  
So if you are looking for more todos, you are free to take care of that.
By the way, I want to rename `scan_types` to `arguments`, as this is much more intuitive.

**Comment by AlexJuca** [comment]
Nice, We can organize a board to deal with missing features. I got some time to spare. I would really like to help with this.

**Comment by AlexJuca** [comment]
I think ```arguments``` is indeed clearer and more intuitive than ```scan types```. I will create a PR with these changes later today.

**Comment by fklement** [comment]
> Nice, We can organize a board to deal with missing features. I got some time to spare. I would really like to help with this.

Good idea. I just created a kanban board here: [Hades - Ora](https://ora.pm/project/199822). 
I'll fill up some tasks until EOD.

**Pull request merged**
